model: vid2vid.edflow_implementations.implementations.TestModel
# dataset: edflow.data.dataset.getDebugDataset
dataset: hbu_journal.data.ntugems.FlatFlowEvaluationSamples
iterator: vid2vid.edflow_implementations.implementations.V2VTrainer

batch_size: 1
spatial_size: 256
box_factor: 1
bottleneck_factor: 2

n_ts: 3

hook_freq: 250
log_freq: 250
ckpt_freq: null
test_freq: 1000
drop_prob: 0.0
num_steps: 100000
