model: vid2vid.edflow_implementations.implementations.TestModel
# dataset: edflow.data.dataset.getDebugDataset
dataset: edflow.data.dataset.getSeqDataset
iterator: vid2vid.edflow_implementations.implementations.Vid2VidEvaluator

debugdataset: 
        dataset: edflow.data.dataset.getSeqDataset
        debug_length: 25

seqdataset:
        dataset: hbu_journal.data.prjoti.TestDataset
        seq_length: &SEQ 3
        seq_step: 1

batch_size: 1
spatial_size: 128
box_factor: 1
bottleneck_factor: 2

n_ts: *SEQ

hook_freq: 250
log_freq: 250
ckpt_freq: null
test_freq: 1000
drop_prob: 0.0
num_steps: 100000
