model: vid2vid.edflow_implementations.implementations.TrainModel
dataset: edflow.data.dataset.getSeqDataset
iterator: vid2vid.edflow_implementations.implementations.V2VTrainer

seqdataset:
        dataset: hbu_journal.data.prjoti.PretrainDataset
        seq_length: 3
        seq_step: 1

batch_size: 5
spatial_size: 128
box_factor: 1
bottleneck_factor: 2

n_ts: 3

hook_freq: 250
log_freq: 250
ckpt_freq: 1000
test_freq: 1000
drop_prob: 0.0
num_steps: 100000
